[package]
name = "Blaze"
version = "1.0.1"
edition = "2021"

[dependencies]
sysinfo = "0.29.0"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
chrono = "0.4"

[[bin]]
name = "blaze"
path = "src/main.rs"
